orbs: # declare what orbs we are going to use
  node: circleci/node@4.9.0 # the node orb provides common node-related configuration
  jira: circleci/jira@1.3.1
  sonarcloud: sonarsource/sonarcloud@1.1.1
  

version: 2.1 # using 2.1 provides access to orbs and other features

workflows:
  build:
    jobs:
      - code-scan:
          context: SonarCloud 
          post-steps:
            - jira/notify
      - test-app:
          requires:
            - code-scan
          post-steps:
            - jira/notify
      - build-image:
          filters:
            branches:
              only: master
          requires:
            - test-app
          post-steps:
            - jira/notify

jobs:
  code-scan:
    docker:
      - image: "cimg/node:16.4"
    steps:
      - checkout
      - sonarcloud/scan

  test-app:
    docker:
      - image: "cimg/node:16.4"
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/auth/node_modules
          override-ci-command: npm install
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package-lock.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

      - run: npm install

      - run: sudo npm install mocha -g

      - run: npm install mocha-junit-reporter # just for CircleCI

      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: mkdir reports

      # Run mocha
      - run:
          name: npm test
          command: mocha src/test/**/*.js --recursive --exit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
          when: always

      # Run coverage report for Code Climate

      - run:
          name: Setup Code Climate test-reporter
          command: |
              # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
          when: always

      - run:
          name: code-coverage
          command: |
              mkdir coverage
              # nyc report requires that nyc has already been run,
              # which creates the .nyc_output folder containing necessary data
              ./node_modules/.bin/nyc report --reporter=text-lcov > coverage/lcov.info
              ./cc-test-reporter after-build -t lcov
          when: always

      # Upload results

      - store_test_results:
          path: reports

      - store_artifacts: # upload test coverage as artifact
          path: ./coverage/lcov.info
          prefix: tests

  build-image:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Login to dockerhub
          command: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Setup docker image
          command: docker build -f dockerfile.dev -t scrappy-dev:${CIRCLE_BUILD_NUM} .
      - run:
          name: tag the docker image to remote repository
          command: docker tag scrappy-dev:${CIRCLE_BUILD_NUM} azax25547/scrappy-dev:${CIRCLE_BUILD_NUM}
      - run:
          name: Push the image to Dockerhub
          command: docker push azax25547/scrappy-dev:${CIRCLE_BUILD_NUM}
# VS Code Extension Version: 1.5.1